import { processSingleTask, processWeeklyPlanPreview, bulkCreateTasks, deferTask } from '../src/services/taskService';
import { generateWeeklyReport } from '../src/services/reportService';

async function runTests() {
  console.log('=== Starting Local Mock Tests ===\n');

  try {
    // 1. Test Single Task Parsing
    console.log('--- Test 1: Single Task Parsing ---');
    const singleTaskInput = 'Làm giao diện đăng nhập cho dự án PRJ226 vào ngày mai, priority High, 2 hours';
    console.log(`Input: "${singleTaskInput}"`);
    const singleTaskResponse = await processSingleTask(singleTaskInput);
    console.log('Response:\n', singleTaskResponse, '\n');

    // 2. Test Weekly Plan Preview
    console.log('--- Test 2: Weekly Plan Preview (FR-7) ---');
    const weeklyPlanInput = 'Tuần này tôi cần làm 2 việc cho PRJ226: 1 là viết API cho user login (mất tầm 3h, High), 2 là viết document cho API đó (mất 1h, Low).';
    console.log(`Input: "${weeklyPlanInput}"`);
    const previewTasks = await processWeeklyPlanPreview(weeklyPlanInput);
    console.log('Parsed Draft Tasks:\n', JSON.stringify(previewTasks, null, 2), '\n');

    // To test bulk creation, you would uncomment the following line (will hit Notion):
    // const bulkCreateResult = await bulkCreateTasks(previewTasks);
    // console.log('Bulk Create Result:\n', bulkCreateResult, '\n');

    // 3. Test Generate Weekly Report
    console.log('--- Test 3: Generate Weekly Report (FR-6) ---');
    console.log('Fetching tasks and generating report...');
    const report = await generateWeeklyReport();
    console.log('Report generated by Gemini PRO:\n', report, '\n');

  } catch (error) {
    console.error('Error during local tests:', error);
  }

  console.log('=== Local Tests Complete ===');
}

runTests();
